storePassword=Eatsflyer@4357
keyPassword=Eatsflyer@4357
keyAlias=upload
storeFile=D:\flutter projects\flyereats-in-merchantapp\android\app\upload-keystore.jks
# storePassword=android
# keyPassword=android
# keyAlias=upload
# storeFile=C:/Users/HP/Downloads/flyereats.clients.jks
